name = "Chemfiles"
uuid = "46823bd8-5fb3-5f92-9aa0-96921f3dd015"
authors = ["Guillaume Fraux <guillaume.fraux@chimie-paristech.fr>"]
version = "0.9.1"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
